FROM maven:3.8.5-eclipse-temurin-8-alpine as BUILD

RUN apk update && apk upgrade && apk add --no-cache \
    bash \
    curl \
    git
    
WORKDIR /build
RUN git clone https://github.com/tamacat/tamacat-core.git
WORKDIR /build/tamacat-core
RUN --mount=type=cache,target=/root/.m2 mvn clean install

WORKDIR /build
RUN git clone https://github.com/tamacat/tamacat-httpd.git
WORKDIR /build/tamacat-httpd
RUN --mount=type=cache,target=/root/.m2 mvn clean install

WORKDIR /build
RUN git clone https://github.com/tamacat/tamacat-blackhole-smtpd.git
WORKDIR /build/tamacat-blackhole-smtpd
RUN --mount=type=cache,target=/root/.m2 mvn clean package


###################################################3
FROM eclipse-temurin:8-jre-alpine

#LABEL maintainer="tamacat.org"

RUN apk update && apk upgrade && apk add --no-cache \
    bash \
    curl

RUN mkdir -p /usr/local/tamacat-blackhole-smtpd/lib
WORKDIR /usr/local/tamacat-blackhole-smtpd

COPY --from=BUILD /build/tamacat-blackhole-smtpd/target/tamacat-blackhole-smtpd-1.0-jar-with-dependencies.jar /usr/local/tamacat-blackhole-smtpd/lib/tamacat-blackhole-smtpd-1.0-jar-with-dependencies.jar

ENV CLASSPATH=/usr/local/tamacat-blackhole-smtpd/lib/tamacat-blackhole-smtpd-1.0-jar-with-dependencies.jar

ENV BIND_PORT=25

EXPOSE ${BIND_PORT}

USER 1001

CMD ["java", "-jar" ,"tamacat-blackhole-smtpd-1.0-jar-with-dependencies.jar"]
